### PR TITLE
fix: `window.backdrop` option is ignored in `.toggle()` API (#77)

### LINKED ISSUE #76: bug: Zen-Mode backdrop does not work properly with colorscheme
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.1

### Operating system/version

MacOS 12.6 Monterey

### Describe the bug

The backdrop of my screen when entering Zen-Mode does not fully reach the bottom of my screen. This happens only when I am using the everforest colorscheme and works fine if I use another one like nightfox. The link directs to the video.
https://www.veed.io/embed/72436a9d-7b3d-4a5d-bccd-4a5c941577db
I would like to know if there are any changes that must be made in order for zen-mode to be compatible with everforest.

### Steps To Reproduce

The default configuration for zen-mode and using the everforest colorscheme.

### Expected Behavior

The backdrop is a full column from the top of the editor to the bottom

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "neanias/everforest-nvim",
  "folke/zen-mode.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("everforest")
-- add anything else here
```

### LINKED ISSUE #77: bug: `window.backdrop` option is ignored in `.toggle()` API
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.8.1

### Operating system/version

Manjaro Linux

### Describe the bug

By using the API `require("zen-mode").toggle({opts})` and passing different options in it,  
it is possible to have different set of options for zen-mode.  

However, while it is possible to set different window sizes,  
the `window.backdrop` value has no effect when used on `toggle()`.  
The background color is not affected by the option at all.

https://github.com/folke/zen-mode.nvim/blob/main/lua/zen-mode/config.lua#L60  
During `setup()`, `M.colors()` is called and the highlight group `ZenBG` is set.
This is not called anywhere else in the codebase, and the highlight will always remain the same.

### Steps To Reproduce

```lua
local zen = require("zen-mode")

zen.setup({
  window = {
    -- pitch black
    backdrop = 0
  }
})

vim.keymap.set("n", "<Space>z", function()
  zen.toggle({
    window = {
      backdrop = 0.9,
    }
  })
end)
```

Try pressing `<Space>z`. Even though backdrop is set to 0.9 in `toggle()`,
the background will be pitch black in zen-mode.

### Expected Behavior

- [`config.colors()`](https://github.com/folke/zen-mode.nvim/blob/main/lua/zen-mode/config.lua#L60 ) should take parameters rather than fetching backdrop value from global options.  
- and it should be called every time `toggle()` is called.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/zen-mode.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

local zen = require("zen-mode")

zen.setup({
  window = {
    -- pitch black
    backdrop = 0
  }
})

vim.keymap.set("n", "<Space>z", function()
  zen.toggle({
    window = {
      backdrop = 0.9,
    }
  })
end)
```

### PR DESCRIPTION
**Pull request by WieeRd**
fixes #76
fixes #77
- `config.colors()` now has optional parameter `options`.
- `view.open()` will call `config.colors()` when entering zen-mode.

This will allow use to:
- have correct highlight group (`ZenBG`) after colorscheme change.
- respect `backdrop` value passed to `require("zen-mode").toggle()`

### CODE REVIEW

**Comment by WieeRd** [comment]
@folke I know you're probably busy with `lazy.nvim` stuffs lately, 
but can you take a quick look at this please?  
It's a really simple fix that does not break anything and solves 2 issues at once.

File: lua/zen-mode/view.lua [hunk 1]
```diff
@@ -74,6 +74,7 @@ end
 
 function M.open(opts)
   if not M.is_open() then
+    config.colors(opts)
```
Comment (folke) [inline lua/zen-mode/view.lua:77]: this should move to the `M.create` function, right under the `opts = `, to make sure the opts object has all the options.

Your code would give an error with `toggle({})` for example.

**Review by folke — CHANGES_REQUESTED** [review]

File: lua/zen-mode/view.lua (hunk 1 above)
Comment (WieeRd) [reply lua/zen-mode/view.lua:77]: Oh, how have I not tested that? I'll fix it right now.

**Comment by WieeRd** [comment]
@folke Fixed and tested again with/without options. Everything works as intended now.

**Comment by folke** [comment]
Thank you!
